def label = "mypod-${UUID.randomUUID().toString()}"
podTemplate(label: label, cloud: 'kubernetes',
  containers: [
    containerTemplate(
        name: 'jnlp', 
        image: 'registry-internal.cn-hangzhou.aliyuncs.com/gionee-library/jenkins-slaves:latest', 
        alwaysPullImage: false, 
        args: '${computer.jnlpmac} ${computer.name}'),
    containerTemplate(
        name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
  ],volumes: [
     hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')
  ]) {

    node(label) {
        stage('build') {
            git url: 'https://github.com/hjue/springboot-jenkins-demo.git'
            sh 'gradle --version'
            sh 'gradle -x test build'
        }
    }
}
